// Section 14's lab: The Neighbor Vote. KNN's own live mechanism -- distance,
// sort, vote -- with a second, hidden layer showing the curse of
// dimensionality break that mechanism in front of you. Hidden coordinates
// are generated by a fixed, deterministic formula, never live randomness.

const POINTS_0701 = [
  { id: 'A', x1: 1, x2: 4, y: 0 },
  { id: 'B', x1: 2, x2: 3, y: 0 },
  { id: 'C', x1: 3, x2: 3, y: 1 },
  { id: 'D', x1: 4, x2: 2, y: 1 },
  { id: 'E', x1: 6, x2: 1, y: 1 },
  { id: 'G', x1: 0.5, x2: 2.2, y: 0 },
  { id: 'H', x1: 1.5, x2: 1, y: 0 },
  { id: 'I', x1: 5, x2: 4, y: 1 },
  { id: 'J', x1: 2.5, x2: 4.5, y: 1 },
  { id: 'K', x1: 5.5, x2: 2.5, y: 1 },
]

const QX1_DEFAULT_0701 = 2.6
const QX2_DEFAULT_0701 = 3.1
const K_DEFAULT_0701 = 1
const D_DEFAULT_0701 = 2

function extraCoord_0701(i, j) {
  return ((((i * 613 + j * 7919) * 48271) % 2147483647) / 2147483647) * 8 - 4
}

function distSq_0701(pointIndex, point, qx1, qx2, d) {
  let s = (qx1 - point.x1) ** 2 + (qx2 - point.x2) ** 2
  if (d > 2) {
    for (let j = 3; j <= d; j++) s += extraCoord_0701(pointIndex, j) ** 2
  }
  return s
}

function nearestK_0701(qx1, qx2, k, d) {
  const withDist = POINTS_0701.map((p, i) => ({ ...p, distSq: distSq_0701(i, p, qx1, qx2, d) }))
  withDist.sort((a, b) => a.distSq - b.distSq || POINTS_0701.indexOf(a) - POINTS_0701.indexOf(b))
  const neighbors = withDist.slice(0, k)
  const votes1 = neighbors.filter(n => n.y === 1).length
  const votes0 = neighbors.length - votes1
  return { ranked: withDist, neighbors, votes1, votes0, predicted: votes1 > votes0 ? 1 : 0 }
}

const advancedLesson0701 = document.querySelector('#advanced-lesson')
function syncAdvancedTarget0701() { if (advancedLesson0701) advancedLesson0701.open = location.hash === '#advanced-lesson' || /^#s(?:0[1-9]|1[0-9]|2[0-4])$/.test(location.hash) }
addEventListener('hashchange', syncAdvancedTarget0701)
syncAdvancedTarget0701()

// -- Plot geometry, reused verbatim from Concept 06's own wgBoundaryPlot_0606. --
const X0_0701 = 70, X1PX_0701 = 430, Y0_0701 = 40, Y1_0701 = 280
const X1_MIN_0701 = 0, X1_MAX_0701 = 7, X2_MIN_0701 = 0, X2_MAX_0701 = 5

function pxX1_0701(x1) { return X0_0701 + (x1 - X1_MIN_0701) / (X1_MAX_0701 - X1_MIN_0701) * (X1PX_0701 - X0_0701) }
function pxX2_0701(x2) { return Y1_0701 - (x2 - X2_MIN_0701) / (X2_MAX_0701 - X2_MIN_0701) * (Y1_0701 - Y0_0701) }

function axisFrame0701() {
  const xTicks = [0, 1, 2, 3, 4, 5, 6, 7].map(x1 => {
    const px = pxX1_0701(x1).toFixed(1)
    return `<line x1="${px}" y1="${Y1_0701}" x2="${px}" y2="${Y1_0701 + 5}" stroke="currentColor" stroke-width="1"/><text x="${px}" y="${Y1_0701 + 16}" text-anchor="middle" font-size="7">${x1}</text>`
  }).join('')
  const yTicks = [0, 1, 2, 3, 4, 5].map(x2 => {
    const py = pxX2_0701(x2).toFixed(1)
    return `<line x1="${X0_0701 - 5}" y1="${py}" x2="${X0_0701}" y2="${py}" stroke="currentColor" stroke-width="1"/><text x="${X0_0701 - 9}" y="${(Number(py) + 2.5).toFixed(1)}" text-anchor="end" font-size="7">${x2}</text>`
  }).join('')
  return `
    <line x1="${X0_0701}" y1="${Y0_0701}" x2="${X0_0701}" y2="${Y1_0701}" stroke="currentColor" stroke-width="1.2"/>
    <line x1="${X0_0701}" y1="${Y1_0701}" x2="${X1PX_0701}" y2="${Y1_0701}" stroke="currentColor" stroke-width="1.2"/>
    ${xTicks}${yTicks}
    <text x="${(X0_0701 + X1PX_0701) / 2}" y="${Y1_0701 + 30}" text-anchor="middle" font-size="7.5" font-weight="700">x1 = prior_contact_attempts</text>
    <text x="18" y="${(Y0_0701 + Y1_0701) / 2}" text-anchor="middle" font-size="7.5" font-weight="700" transform="rotate(-90 18 ${(Y0_0701 + Y1_0701) / 2})">x2 = satisfaction_score</text>
  `
}

function neighborPlotSvg_0701({ qx1, qx2, k, d, titleId, titleText, descText, rankLabels }) {
  const result = nearestK_0701(qx1, qx2, k, d)
  const neighborIds = new Set(result.neighbors.map(n => n.id))
  const points = POINTS_0701.map(p => {
    const isNeighbor = neighborIds.has(p.id)
    const cx = pxX1_0701(p.x1).toFixed(1), cy = pxX2_0701(p.x2).toFixed(1)
    const fill = p.y === 1 ? 'var(--teal)' : 'var(--orange)'
    let extraLabel = ''
    if (rankLabels) {
      const rankIdx = result.neighbors.findIndex(n => n.id === p.id)
      if (rankIdx >= 0) {
        const distVal = Math.sqrt(result.neighbors[rankIdx].distSq)
        extraLabel = `<text x="${cx}" y="${(Number(cy) - 10).toFixed(1)}" text-anchor="middle" font-size="6.5" font-weight="700">#${rankIdx + 1} d=${distVal.toFixed(2)}</text>`
      }
    }
    const connector = isNeighbor ? `<line x1="${pxX1_0701(qx1).toFixed(1)}" y1="${pxX2_0701(qx2).toFixed(1)}" x2="${cx}" y2="${cy}" stroke="var(--ink)" stroke-width="1.2" stroke-dasharray="3,3"/>` : ''
    return `
      ${connector}
      <circle cx="${cx}" cy="${cy}" r="5" fill="${fill}" opacity="${isNeighbor ? 1 : 0.35}" stroke="var(--ink)" stroke-width="${isNeighbor ? 1.2 : 0}"/>
      <text x="${cx}" y="${(Number(cy) + 14).toFixed(1)}" text-anchor="middle" font-size="7" font-weight="700">${p.id}</text>
      ${extraLabel}
    `
  }).join('')
  const qx = pxX1_0701(qx1).toFixed(1), qy = pxX2_0701(qx2).toFixed(1)
  return `
    <svg class="vector-plane" viewBox="0 0 460 320" role="img" aria-labelledby="${titleId}-title ${titleId}-desc">
      <title id="${titleId}-title">${titleText}</title>
      <desc id="${titleId}-desc">${descText}</desc>
      <g font-family="IBM Plex Mono, monospace" fill="currentColor">
        ${axisFrame0701()}
        ${points}
        <circle cx="${qx}" cy="${qy}" r="7" fill="none" stroke="var(--ink)" stroke-width="2"/>
        <line x1="${(Number(qx) - 10).toFixed(1)}" y1="${qy}" x2="${(Number(qx) + 10).toFixed(1)}" y2="${qy}" stroke="var(--ink)" stroke-width="1"/>
        <line x1="${qx}" y1="${(Number(qy) - 10).toFixed(1)}" x2="${qx}" y2="${(Number(qy) + 10).toFixed(1)}" stroke="var(--ink)" stroke-width="1"/>
        <text x="${qx}" y="${(Number(qy) - 12).toFixed(1)}" text-anchor="middle" font-size="7" font-weight="700">Q</text>
      </g>
    </svg>
  `
}

function renderNeighborStatic1_0701() {
  const wrap = document.querySelector('#wgNeighborStatic1_0701')
  if (!wrap) return
  wrap.innerHTML = neighborPlotSvg_0701({
    qx1: QX1_DEFAULT_0701, qx2: QX2_DEFAULT_0701, k: 5, d: 2,
    titleId: 'c0701-b03-svg',
    titleText: 'A query point and ten stored rows, with the five nearest highlighted',
    descText: 'A scatter plot with ten labeled points colored by class. Five points closest to the query are highlighted with dashed connector lines; the rest are dimmed.',
    rankLabels: false,
  })
}
function renderNeighborStatic2_0701() {
  const wrap = document.querySelector('#wgNeighborStatic2_0701')
  if (!wrap) return
  wrap.innerHTML = neighborPlotSvg_0701({
    qx1: QX1_DEFAULT_0701, qx2: QX2_DEFAULT_0701, k: 5, d: 2,
    titleId: 'c0701-s07-svg',
    titleText: 'The five nearest neighbors, ranked and labeled by distance',
    descText: 'The same plot as the beginner figure, with each of the five nearest points labeled by its own rank and exact distance from the query.',
    rankLabels: true,
  })
}

// -- Interactive lab (s14): The Neighbor Vote. --
const qx1Slider_0701 = document.querySelector('#wgQx1_0701')
const qx2Slider_0701 = document.querySelector('#wgQx2_0701')
const qx1Out_0701 = document.querySelector('#wgQx1Out_0701')
const qx2Out_0701 = document.querySelector('#wgQx2Out_0701')
const kButtons_0701 = [...document.querySelectorAll('#s14 [data-k]')]
const dButtons_0701 = [...document.querySelectorAll('#s14 [data-d]')]
const resetBtn_0701 = document.querySelector('#wgReset_0701')
const plotWrap_0701 = document.querySelector('#wgNeighborPlot_0701')
const readout_0701 = document.querySelector('#wgReadout_0701')
const verdict_0701 = document.querySelector('#wgVerdict_0701')

let currentK_0701 = K_DEFAULT_0701
let currentD_0701 = D_DEFAULT_0701

function syncButtons_0701() {
  kButtons_0701.forEach(btn => btn.classList.toggle('active', Number(btn.dataset.k) === currentK_0701))
  dButtons_0701.forEach(btn => btn.classList.toggle('active', Number(btn.dataset.d) === currentD_0701))
}

function renderLab_0701() {
  if (!qx1Slider_0701 || !qx2Slider_0701) return
  const qx1 = Number(qx1Slider_0701.value)
  const qx2 = Number(qx2Slider_0701.value)
  if (qx1Out_0701) qx1Out_0701.textContent = qx1.toFixed(1)
  if (qx2Out_0701) qx2Out_0701.textContent = qx2.toFixed(1)

  const result = nearestK_0701(qx1, qx2, currentK_0701, currentD_0701)

  if (plotWrap_0701) {
    plotWrap_0701.innerHTML = neighborPlotSvg_0701({
      qx1, qx2, k: currentK_0701, d: currentD_0701,
      titleId: 'c0701-lab-svg',
      titleText: 'Live neighbor plot, updated as the sliders and k/d controls move',
      descText: 'A live version of the scatter plot, redrawn from the current query position, k, and hidden-dimension count.',
      rankLabels: false,
    })
  }

  if (readout_0701) {
    const neighborList = result.neighbors.map((n, i) => `<div><span>NEAREST #${i + 1}</span><b>${n.id} (d=${Math.sqrt(n.distSq).toFixed(3)})</b></div>`).join('')
    readout_0701.innerHTML = `
      <div><span>QUERY</span><b>(${qx1.toFixed(1)}, ${qx2.toFixed(1)})</b></div>
      <div><span>k</span><b>${currentK_0701}</b></div>
      <div><span>d</span><b>${currentD_0701}${currentD_0701 > 2 ? ' (2 shown + ' + (currentD_0701 - 2) + ' fixed hidden)' : ''}</b></div>
      <div><span>VOTE</span><b>${result.votes1} relief, ${result.votes0} no relief</b></div>
      <div class="wide"><span>PREDICTION</span><b>${result.predicted === 1 ? 'Relief' : 'No relief'}</b></div>
      ${neighborList}
    `
  }

  if (verdict_0701) {
    let cls = 'verdict-green', msg = ''
    if (currentD_0701 === 2) {
      cls = 'verdict-green'
      msg = 'd=2: a pure lookup among the two real, visible features -- no weight vector anywhere, unlike Concepts 06/07\'s own fitted models.'
    } else if (currentD_0701 === 10) {
      cls = 'verdict-amber'
      msg = 'd=10: 8 hidden fixed coordinates are now part of every distance calculation -- the vote may already be drifting from what looks closest on screen.'
    } else if (currentD_0701 === 50) {
      cls = 'verdict-amber'
      msg = 'd=50: 48 hidden coordinates are now in play -- the dashed connector lines may reach past points that look visibly closer than the ones actually chosen.'
    } else {
      cls = 'verdict-red'
      msg = 'd=200: 198 hidden coordinates dominate the distance calculation -- the highlighted "nearest" neighbors can look essentially arbitrary relative to on-screen closeness, the same collapse Section 10\'s own worked example measured as a shrinking max/min ratio.'
    }
    verdict_0701.className = 'gate-verdict ' + cls
    verdict_0701.textContent = msg
  }
}

qx1Slider_0701?.addEventListener('input', renderLab_0701)
qx2Slider_0701?.addEventListener('input', renderLab_0701)
kButtons_0701.forEach(btn => btn.addEventListener('click', () => {
  currentK_0701 = Number(btn.dataset.k)
  syncButtons_0701()
  renderLab_0701()
}))
dButtons_0701.forEach(btn => btn.addEventListener('click', () => {
  currentD_0701 = Number(btn.dataset.d)
  syncButtons_0701()
  renderLab_0701()
}))
resetBtn_0701?.addEventListener('click', () => {
  if (qx1Slider_0701) qx1Slider_0701.value = String(QX1_DEFAULT_0701)
  if (qx2Slider_0701) qx2Slider_0701.value = String(QX2_DEFAULT_0701)
  currentK_0701 = K_DEFAULT_0701
  currentD_0701 = D_DEFAULT_0701
  syncButtons_0701()
  renderLab_0701()
})

renderNeighborStatic1_0701()
renderNeighborStatic2_0701()
syncButtons_0701()
renderLab_0701()
